### PR TITLE
Minor improvements in codes and formatting  # 3

### PR DESCRIPTION
**Pull request by Yousha**

### CODE REVIEW

**Review by CodeAlDente — COMMENTED** [review]
Usuage of `MAX_STRING_INPUT_TEXT` is needed for the whole string, not only for e.g. `Reason`.

We should set a limit for texts that can be provided in the command like `Reason` on `/kick` and check if the length of it is too long and check for the total length of the string including command and paramters is lower than `MAX_STRING_INPUT_TEXT`.

But this is a job for later, see #97.

**Review by CodeAlDente — COMMENTED** [review]
The extra three lines after a command are intended for a better overview.

**Comment by CodeAlDente** [comment]
Thank you for your contribution! :+1:

**Comment by Yousha** [comment]
> 
> 
> The extra three lines after a command are intended for a better overview.

Yes I wanted to leave them like that, but I found many lines with 2 blank lines or even 1
That's why changed them ALL to 1 line.

YW

**Pull request merged**
